version: "3.7"
networks:
  banco:
  back:
  k6:
  grafana:

services:

  postgres:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - ./envs/postgres.env
    networks:
      - banco

  django:
    build:
      dockerfile: ./docker/dockerfile
      context: .
    command: python /source/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./source:/source
      - ./k6:/k6
    env_file:
      - ./envs/postgres.env
      - ./envs/.env
    environment:
      - DEBUG=True
    ports:
      - 8000:8000
    networks:
      - back
      - banco
    depends_on:
      - postgres

  influxdb:
    image: influxdb:1.8-alpine
    networks:
      - k6
      - grafana
    ports:
      - 8086:8086
    environment:
      - INFLUXDB_DB=k6

  grafana:
    image: grafana/grafana:latest
    networks:
      - grafana
    ports:
      - 3000:3000
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    volumes:
      - ./k6/dashboards:/var/lib/grafana/dashboards
      - ./k6/grafana-dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
      - ./k6/grafana-datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml

  k6-integrado:
    image: loadimpact/k6:latest
    networks:
      - k6
      - back
    ports:
      - 6565:6565
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
      - API_BASE=https://django:8000/
    volumes:
      - ./k6/scripts:/scripts
